### ISSUE TITLE
What is model for Resnet 110

### ISSUE THREAD

**Issue by mjohn123** [fish145/ResNet-on-Cifar10#2]
Hello, It is very interesting in your result. However, up to 110 layers, they often use identity	skip connections in "Identity Mappings in Deep Residual Networks". They also show very performance using the network. Do you try to implement it in caffe? Thanks

**Comment by junyuseu** [comment]
"In our case, the shortcut connections simply perform identity mapping, and their outputs are added to the outputs of the stacked layers". So the skip connections in ResNets are only used as identity mappings

**Comment by mjohn123** [comment]
Yes, I know it. My question just asks about your implementation of identity mapping. Because it can show some benefit when we working with more than 100 layers

**Comment by junyuseu** [comment]
we use the layer itself as the identity mapping,  the same as what Kaiming do.
