### ISSUE TITLE
the meanfile?

### ISSUE THREAD

**Issue by yanyanxixi** [fish145/ResNet-on-Cifar10#3]
mean_file: "../../mean.binaryproto"
 crop_size: 28

hi 
i have a problem that if meanfile and crop_size used at the same time , is the mean_file usefully? 
the train sample size 32x32   mean_file size will be 32x32,how to subtract 28x28

**Comment by junyuseu** [comment]
You can see the code of caffe/src/caffe/data_transformer.cpp.
if you use meanfile and crop_size the same time, it will first check the crop_size and meanfile size before transformation. If there is no problem, Caffe will first crop 28x28(as you say) blob from the 32x32 blob, then subtract the corresponding value according to the meanfile.
The detail can be seen in the code.
